# IAM User access configuration
AWS_ACCESS_KEY="HIDDEN"
AWS_SECRET_ACCESS_KEY="HIDDEN"
AWS_REGION="us-east-1"

# S3 Bucket for photo objects
PHOTOGALLERY_S3_BUCKET_NAME="HIDDEN"

# MySQL Configuration
RDS_DB_HOSTNAME="HIDDEN"
RDS_DB_USERNAME='HIDDEN'
RDS_DB_PASSWORD='HIDDEN'
RDS_DB_NAME='HIDDEN'

# DynamoDB Table
DYNAMODB_TABLE='HIDDEN'
USER_DYNAMODB_TABLE ='HIDDEN'

###### INSERT NEW ENVIRONMENT VARIEABLES HERE ######

HASH_SERIALIZER = 'HIDDEN'

CURRENT_URL = 'HIDDEN'
EMAIL_SOURCE = 'HIDDEN'
####################################################
